---

# Most Linux distros in the RedHat family use YUM

- name: install packages for Go development (yum)
  become: yes
  yum: name="{{ golang_packages }}" state=present
  when: ansible_pkg_mgr == 'yum'

# Fedora 23 and higher use DNF

- name: install packages for Go development (dnf)
  become: yes
  dnf: name="{{ golang_packages }}" state=present
  when: ansible_pkg_mgr == 'dnf'

# Debian distros

- debug:
    msg: "adding repo = >{{ golang_repo }}<"
  when: golang_repo is defined and golang_repo != ''

- name: add debian repository
  become: yes
  apt_repository: repo="{{ golang_repo }}" state=present
  when: golang_repo is defined and golang_repo != ''

- name: install packages for Go development (apt)
  become: yes
  apt: name="{{ golang_packages }}" state=present
       update_cache=yes
  when: ansible_pkg_mgr == 'apt'
