---

# -------------------------------------------------------------
#  Prepare to download
# -------------------------------------------------------------

- block:

  - name: query for latest Go version
    run_once: true
    local_action: uri
      url="{{ golang_latest_version_url }}"
      return_content=yes
    register: latest_go_version
    when: golang_package_version == "auto"

  - name: set golang version to latest
    set_fact:
      golang_package_version: "{{ latest_go_version.content }}"
  
  when: golang_package_version == "auto"

- name: prepare go package download url
  set_fact:
    golang_download_url: "{{ golang_package_url }}/{{ golang_package_version }}.{{ golang_package_os }}-{{ golang_package_arch }}.tar.gz"
  when: golang_download_url is not defined or golang_download_url == ""

- name: get filename of Golang distribution file
  set_fact:
    golang_package_file: "{{ golang_download_url | basename }}"

# -------------------------------------------------------------
#  Download
# -------------------------------------------------------------

- debug: var=golang_download_url

- name: create local download folder
  local_action: file
                name="{{ download_cache_dir }}"
                state=directory

- name: check if Go distribution file was already downloaded
  run_once: true
  local_action: stat
                path="{{ download_cache_dir }}/{{ golang_package_file }}"
  register: downloaded_file

- name: download Go distribution file
  run_once: true
  local_action: get_url
                url="{{ golang_download_url }}"
                dest="{{ download_cache_dir }}"
  when: not downloaded_file.stat.exists

# -------------------------------------------------------------
#  Install
# -------------------------------------------------------------

# package(s) required to unarchive the distribution file

- include: prerequisites.yml

- name: install Golang from distribution file
  become: yes
  unarchive: src="{{ download_cache_dir }}/{{ golang_package_file }}"
             dest="{{ golang_install_dir }}"
             creates="{{ golang_install_dir }}/go"
             keep_newer=True
