---

- include: install_download.yml
  when: "{{ golang_install_from == 'download' }}"

- include: install_repo.yml
  when: "{{ golang_install_from == 'repo' }}"

- fail: msg="invalid setting for golang installation source"
  when: "{{ golang_install_from != 'repo' and golang_install_from != 'download' }}"