---
# Install required packages

# Most Linux distros in the RedHat family use YUM

- name: install required packages (yum)
  become: yes
  yum: name="{{ required_packages }}" state=present
  when: ansible_pkg_mgr == 'yum'

# Fedora 23 and higher use DNF

- name: install required packages (dnf)
  become: yes
  dnf: name="{{ required_packages }}" state=present
  when: ansible_pkg_mgr == 'dnf'

# for Debian distros

- name: install required packages (apt)
  become: yes
  apt: name="{{ required_packages }}" state=present
       update_cache=yes
  when: ansible_pkg_mgr == 'apt'