---
# ---------------------------------------------------------------------
#  Provision Virtual Machine and deploy development software
# ---------------------------------------------------------------------

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud:      aws
    vm_count:   1
    vm_tags:
        name:           "Development machine"
        purpose:        "Work on home assignments"
        provisioner:    "Ansible"

    cloud_inventory_group:      dev

  roles:
    - { role: provision-cloud,  tags: "vm" }

# ---------------------------------------------------------------------
#  Optional: make sure Python 2 is available on the Virtual Machines
# ---------------------------------------------------------------------

- hosts: dev
  gather_facts: false
  roles:
    - { role: min-install,      tags: "min-install" }

# ---------------------------------------------------------------------
#  Deploy software to Virtual Machines
# ---------------------------------------------------------------------

- hosts: dev
  roles:
    - user-env
    - dev-env
    - { role: sublime-text,     when: install == "sublime" }
    - { role: cpp-dev,          when: install == "cpp"     }
    - { role: ruby-dev,         when: install == "ruby"    }
    - { role: golang,           when: install == "go" or install == "golang" }

# ---------------------------------------------------------------------
# eof
#
