---
# ---------------------------------------------------------------------
#  Provision Virtual Machine and deploy development software
# ---------------------------------------------------------------------

- name: provision virtual machine(s)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud:      aws
    vm_count:   1
    vm_tags:
        name:           "Development machine(s)"
        purpose:        "Code and devops experiments"
        provisioner:    "Ansible"

    cloud_inventory_group:      dev

  roles:
    - { role: provision-cloud,  tags: "vm" }

# -----------------------------

- name: install required software to execute Ansible tasks on the remote hosts
  hosts: dev
  gather_facts: false
  roles:
    - { role: min-install,      tags: "min-install" }

# -----------------------------

- name: install code development software
  hosts: dev
  roles:
    - user-env
    - dev-env
    - { role: sublime-text,     when: install_sublime }
    - { role: cpp-dev,          when: install_cpp     }
    - { role: ruby-dev,         when: install_ruby    }
    - { role: golang,           when: install_go      }
