---
# ---------------------------------------------------------------------
#  Provision Virtual Machine and deploy development software
# ---------------------------------------------------------------------

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud:      aws
    vm_count:   3
    vm_tags:
        name:           "Development machine"
        purpose:        "Work on home assignments"
        provisioner:    "Ansible"

  roles:
    - provision-cloud

# ---------------------------------------------------------------------
#  Optional: make sure Python 2 is available on the Virtual Machines
# ---------------------------------------------------------------------

- hosts: cloud
  gather_facts: false
  roles:
    - min-install

# ---------------------------------------------------------------------
#  Deploy software to Virtual Machines
# ---------------------------------------------------------------------

- hosts: cloud
  roles:

    - { role: sublime-text,   when: install == "sublime" }
    - { role: cpp-dev,        when: install == "cpp"     }
    - { role: ruby-dev,       when: install == "ruby"    }

# ---------------------------------------------------------------------
# eof
#