---
# ---------------------------------------------------------------------
#  Provision cluster of Virtual Machine (to install Serf)
# ---------------------------------------------------------------------

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud:      aws
    vm_count:   3
    vm_tags:
        name:           "Serf cluster"
        purpose:        "Experiment with serf"
        provisioner:    "Ansible"

    cloud_inventory_group:      serf

  roles:
    - { role: provision-cloud,  tags: "vm" }

# ---------------------------------------------------------------------
#  Optional: make sure Python 2 is available on the Virtual Machines
# ---------------------------------------------------------------------

- hosts: serf
  gather_facts: false
  roles:
    - { role: min-install,      tags: "min-install" }

# ---------------------------------------------------------------------
#  Deploy Serf to Virtual Machines
# ---------------------------------------------------------------------

- hosts: serf
  roles:
    - { role: serf,             tags: "serf" }

# ---------------------------------------------------------------------
# eof
#