---
# Install required packages on Fedora Linux

- name: determine Fedora release
  raw: cut -d" " -f3 {{ fedora_release_file }}
  register: fedora_release
  ignore_errors: true

- name: report error if target machine is not Fedora
  debug: msg="Target machine is not Fedora"
  when: fedora_release.rc != 0

- set_fact:
    fedora_version: "{{ fedora_release.stdout | int }}"
  when: fedora_release.rc == 0

# Fedora 22 and lower use yum ----------------------------

- name: (yum) install minimum required packages with CLI command
  become: yes
  raw: yum -y install {{ item }}
  with_items: "{{ min_packages[ 'fedora_yum' ] }}"
  when: fedora_release.rc == 0 and fedora_version < fedora_version_uses_dnf
  register: python2_install_yum

# Fedora 23 and higher use DNF ---------------------------

- name: (dnf) install minimum required packages with CLI command
  become: yes
  raw: dnf -y install {{ item }}
  with_items: "{{ min_packages[ 'fedora_dnf' ] }}"
  when: fedora_release.rc == 0 and fedora_version >= fedora_version_uses_dnf
  register: python2_install_dnf

# record the fact that python2 is installed

- set_fact:
    python2_installed:    True