---

# Most Linux distros in the RedHat family use YUM

- name: install Ruby build required packages (yum)
  become: yes
  yum: name="{{ item }}" state=present
  with_items: "{{ ruby_dep_packages }}"
  when: ansible_pkg_mgr == "yum"

# Fedora 23 and higher use DNF

- name: install Ruby build required packages (dnf)
  become: yes
  dnf: name="{{ item }}" state=present
  with_items: "{{ ruby_dep_packages }}"
  when: ansible_pkg_mgr == "dnf"

# for Debian distros

- name: install Ruby build required packages (apt)
  become: yes
  apt: name="{{ item }}" state=present
       update_cache=yes
  with_items: "{{ ruby_dep_packages }}"
  when: ansible_pkg_mgr == "apt"