---
# Install rbenv

- name: clone the rbenv git repo into ~/.rbenv
  git: repo={{ rbenv_repo }}
       dest="{{ ansible_user_dir }}/.rbenv"
       accept_hostkey=yes

- name: add the install command to rbenv
  git: repo={{ rbenv_install_repo }}
       dest="{{ ansible_user_dir }}/.rbenv/plugins/ruby-build"
       accept_hostkey=yes

- name: update profile (rbenv)
  lineinfile: dest="{{ ansible_user_dir }}/{{ shell_profile }}"
              line="{{ item }}"
              state=present
              insertafter=EOF
  with_items: "{{ profile_addons }}"
