---
# Install and set up Serf agents

- include: download.yml

- include: prerequisites.yml
  become: yes

# installation --------------------------------------------------------

- name: install Serf from archive file
  become: yes
  unarchive: src="{{ download_cache_dir }}/{{ serf_pkg }}"
             dest="{{ install_dir }}"
             creates="{{ install_dir }}/serf"
             keep_newer=True
  notify:
    - restart {{ service_name }}

# configuration -------------------------------------------------------

- include: encryption.yml

# create service ------------------------------------------------------

- include: service_systemd.yml
  become: yes
  when: ansible_service_mgr == "systemd"

- include: service_upstart.yml
  become: yes
  when: ansible_service_mgr == "upstart"

# - include: service_init.yml
#   become: yes
#   when: ansible_service_mgr == "init"