---
# Install required packages

# Most Linux distros in the RedHat family use YUM

- name: install required packages (yum)
  yum: name="{{ item }}" state=present
  with_items: "{{ required_packages }}"
  when: ansible_pkg_mgr == "yum"

# Fedora 23 and higher use DNF

- name: install required packages (dnf)
  dnf: name="{{ item }}" state=present
  with_items: "{{ required_packages }}"
  when: ansible_pkg_mgr == "dnf"

# for Debian distros

- name: install required packages (apt)
  apt: name="{{ item }}" state=present
       update_cache=yes
  with_items: "{{ required_packages }}"
  when: ansible_pkg_mgr == "apt"