---
# Deploy upstart service

- name: install service configuration files
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            owner=root group=root mode="u=rw,g=r,o=r"
  with_items:
    - { src: "{{ service_name }}-config.j2",      dest: "/etc/default/{{ service_name }}"       }
    - { src: "{{ service_name }}-config-json.j2", dest: "/etc/default/{{ service_name }}.json"  }
  notify:
    - restart {{ service_name }}

- name: install service management file
  template: src="{{ service_name }}-upstart.j2"
            dest="/etc/init/{{ service_name }}.conf"
            owner=root group=root mode="u=rw,g=r,o=r"
  notify:
    - enable {{ service_name }}
    - restart {{ service_name }}