---
# Software packages to install for C++ development

cpp_packages_by_os:
  Ubuntu:
    - g++
#  RedHat:
#  CentOS:
  Fedora:
    - gcc-g++
  default:
    - gcc-c++

cpp_packages:     "{{ lookup('by_dist', 'cpp_packages') }}"