---
# Software packages to install for C++ development

cpp_packages_by_os:
  Ubuntu:
    # '14.04':
    #     - tbd
    default:
        - g++
  RHEL:
  CentOS:
  Fedora:
    - gcc-c++
  default:
    - gcc-g++

cpp_packages:     "{{ lookup('by_dist', 'cpp_packages') }}"