---
# Install CPP packages

# - set_fact:
#     extra_packages:   "{{ cpp_extra_packages[ extra ] | default([]) }}"

- name: install packages for C++ development (yum)
  become: yes
  yum: name="{{ cpp_packages + cpp_extra_packages[ extra ] }}" state=present
  when: ansible_pkg_mgr == "yum"

# Fedora 23 and higher use DNF

- name: install packages for C++ development (dnf)
  become: yes
  dnf: name="{{ cpp_packages + cpp_extra_packages[ extra ] }}" state=present
  when: ansible_pkg_mgr == "dnf"

# for Debian distros

- name: install packages for C++ development (apt)
  become: yes
  apt: name="{{ cpp_packages + cpp_extra_packages[ extra ] }}" state=present
       update_cache=yes
  when: ansible_pkg_mgr == "apt"