---

golang_install_from:        "download"
# golang_install_from:        "repo"

# installation from download site
# golang_download_url:       "https://storage.googleapis.com/golang/go1.16.1.linux-amd64.tar.gz"
golang_latest_version_url:  "https://golang.org/VERSION?m=text"

golang_package_url:         "https://storage.googleapis.com/golang"
golang_package_version:     "auto"
golang_package_arch:        "amd64"
golang_package_os:          "linux"

golang_install_dir:         "/usr/local"

# installation from repo
# golang_repo:
golang_packages:
  - golang

required_packages:
