---

# useful definitions ------------------------------------------

home_dir:           "{{ lookup('env','HOME') }}"
current_dir:        "{{ lookup('env','PWD') }}"

service_name:       "serf"

install_dir:        "/usr/local/bin"
serf_log_level:     "info"

cluster_name:       "ansible-serf"

advertise_name:     false

# source of the encryption key can be:
#   - provided directly in <var.yml> file
#   - stored in flat file under files/
#   - generated during deployment

# encryption_key:         "..."
# encryption_key_file:    "serf-encryption.key"
reuse_encryption_key:     false

# required minimal set of tools
required_packages:
  - unzip

sysconfig_dir_by_os:
  default:      "/etc/sysconfig"
  Ubuntu:       "/etc/default"
  # RedHat:
  # CentOS:
  # Fedora:

sysconfig_dir:              "{{ lookup('by_dist', 'sysconfig_dir') }}"

serf_username:              serf
serf_groupname:             daemon

# download params -----------------------------------------------------

serf_version:               "0.8.2"
serf_download_from:         local

## match cpu arch to hashi naming convention
hashicorp_architecture_map:
  x86_64:   amd64
  armv7l:   arm
  aarch64:  arm64

serf_architecture:          "{{ hashicorp_architecture_map[ ansible_architecture ] }}"

hashicorp_download_url:     "https://releases.hashicorp.com"

serf_zip_url:               "{{ hashicorp_download_url }}/serf/{{ serf_version }}/serf_{{ serf_version }}_linux_{{ serf_architecture }}.zip"
serf_checksum_file_url:     "{{ hashicorp_download_url }}/serf/{{ serf_version }}/serf_{{ serf_version }}_SHA256SUMS"