---
# AWS cloud provisioning config

# use environment variables instead
aws_access_key:
aws_secret_key:
aws_session_token:

aws_region:                 us-west-2

aws_keypair:                "Misho's public key"
aws_vpc_subnet:             subnet-c8b90aac

# Fedora-Cloud-Base-24-20160718.0.x86_64-us-west-2-HVM-standard-0 - ami-f1b17c91
ec2_image:                  ami-f1b17c91
ec2_user:                   fedora
ec2_security_group:         default
ec2_instance_type:          t2.micro

ec2_tags:
    type:   "ec2"

ec2_instance_name_attr:         private_ip_address
ec2_new_instance_name_attr:     private_ip

aws_ec2_create_timeout:     300         # seconds
aws_ec2_startup_timeout:    300         # seconds

aws_ec2_runnable_states:
    - initializing
    - starting
    - running
    - stopping
    - stopped