---

sublime_text_url:               http://c758482.r82.cf2.rackcdn.com
sublime_text_name:              "Sublime%20Text%202.0.2%20x64"
sublime_text_dest:              /usr/local
sublime_text_extract_dir:       "Sublime\ Text\ 2"
sublime_text_dir:               SublimeText2
sublime_text_download_dest:     /tmp

sublime_dep_packages_by_os:
  Ubuntu:
    # '14.04':
    'default':
        - libgtk2.0-0
  RHEL:
  CentOS:
  Fedora:
      - gtk3
  all:              []

sublime_dep_packages:     "{{ lookup('by_dist', 'sublime_dep_packages') }}"